# Propiedades de configuracion de Solvencia 2
# Variables de Entorno
JAVA_HOME=/usr/java/jdk1.7.0_51
export JAVA_HOME
ORACLE_HOME=/u01/oracle
export ORACLE_HOME
PATH=$JAVA_HOME/bin:$ORACLE_HOME:$PATH:$HOME/bin
export PATH

RUTA_BASE=/mnt/solv2vida/CIERRES                                    # Ruta del sistema de ficheros donde esta montada la carpeta CIERRES de la NAS de Negocio
LOG_PATH=/logs                                                      # Ubicacion del fichero de log de ejecucion del script de automatizacion

# Configuracion de Coherence
INIT_PORT=8088
COHERENCE_NODES=12                                                  # Numero de nodos de Coherence a levantar en cada Instancia de Amazon
ENTREGABLES_NODES=1													# Número de nodos levantados para calcular entregables
ENTREGABLES_MEM=3													# Relación de memoria asignada a los nodos entregables frente al resto de motores (>=1)
COHERENCE_CONFIG_FILE=coherence-cache-solvencia-config.xml          # Nombre del fichero de configuracion de caches Coherence
COHERENCE_OVERRIDE_FILE=solvencia-tangosol-coherence-override.xml   # Nombre del fichero de configuración de entorno de Coherence
POF_CONFIG_FILE=pof/solvencia-planificador-pof-config.xml           # Nombre del fichero de configuración de serializacion POF
PARTITIONING_STRATEGY=com.tangosol.net.partition.DefaultKeyPartitioningStrategy      # Estrategia de particionado de claves
COHERENCE_JMX_HOST=localhost

# Configuracion de Amazon
AWS_PROPERTIES_FILE=AwsCredentials_dev.properties                   # Fichero donde se almacenan las credenciales de la cuenta de Amazon
AWS_REGION=us-east-1                                                # Zona de Amazon donde estan desplegadas las instancias
AWS_INSTANCE_ROLE_TAG=Role                                          # Etiqueta a buscar para identificar las instancias
AWS_INSTANCE_ROLE_VALUE=COHERENCE_SERVER                            # Valor de la etiqueta a buscar para identificar las instancias
AWS_NIC_TAG=Name                                                    # Etiqueta a buscar para identificar las interfaces de red
AWS_NIC_VALUE=Interconnect                                          # Valor de la etiqueta a buscar para identificar las interfaces de red

#Configuracion de Proxy
PROXY_CONFIG=
