# Propiedades de configuracion de Solvencia 2
# Variables de Entorno
JAVA_HOME=/usr/java/jdk1.7.0_51
export JAVA_HOME
ORACLE_HOME=/u01/oracle
export ORACLE_HOME
PATH=$JAVA_HOME/bin:$ORACLE_HOME:$PATH:$HOME/bin
export PATH

RUTA_BASE=/mnt/solv2vida/CIERRES                                    # Ruta del sistema de ficheros donde esta montada la carpeta CIERRES de la NAS de Negocio
LOG_PATH=/logs                                                      # Ubicacion del fichero de log de ejecucion del script de automatizacion

# Configuracion de Coherence
INIT_PORT=8088
#COHERENCE_NODES=3                                                   # Numero de nodos de Coherence a levantar en cada Instancia de Amazon
ENTREGABLES_NODES=1                                                 # Numero de nodos levantados para calcular entregables
ENTREGABLES_MEM=1                                                   # Relacion de memoria asignada a los nodos entregables frente al resto de motores (>=1)
COHERENCE_CONFIG_FILE=coherence-cache-solvencia-config.xml          # Nombre del fichero de configuracion de caches Coherence
COHERENCE_OVERRIDE_FILE=solvencia-tangosol-coherence-override.xml   # Nombre del fichero de configuracion de entorno de Coherence
POF_CONFIG_FILE=pof/solvencia-planificador-pof-config.xml           # Nombre del fichero de configuracion de serializacion POF
PARTITIONING_STRATEGY=com.tangosol.net.partition.DefaultKeyPartitioningStrategy      # Estrategia de particionado de claves


#Configuracion de Proxy
#PROXY_CONFIG="-DproxySet=true -DproxyHost=10.229.174.147 -DproxyPort=8080 -Dhttps.proxySet=true -Dhttps.proxyHost=10.229.174.147 -Dhttps.proxyPort=8080"

#Configuracion IP
#Lanzamiento del proceso arranque coherence
#-Dtangosol.coherence.wka=$IP_INTERC1  -Dtangosol.coherence.wka2=$IP_INTERC2 
IP_INTERC1=10.231.111.135
IP_INTERC2=10.231.111.136
IP_INTERC3=10.231.111.137
IP_INTERC4=10.231.111.138
IP_INTERC5=10.231.111.139
IP_INTERC6=10.231.111.140
IP_INTERC7=10.231.111.141
IP_INTERC8=10.231.111.142
IP_INTERC9=10.231.111.143
IP_INTERC10=10.231.111.144
IP_INTERC11=10.231.111.145
IP_INTERC12=10.231.111.146