#raiz=/home/eaguiler/Documentos/eclipse_cvs/Mapfre/Solvencia/entorno_OPEN/
raiz=/explotacion/SOLV2VIDA/
#jar_lib=programas/
jar_lib=programas/produccion/SOLV2VIDA/lib/
#ficheros=ficheros/entrada/
ficheros=ficheros/SOLV2VIDA/CIERRES/
#dir_temporal=ficheros/temporal/
dir_temporal=ficheros/SOLV2VIDA/temporal/
#dir_salida=ficheros/salida/
dir_salida=ficheros/SOLV2VIDA/salida/
#dir_config=ficheros/entrada/config
dir_config=programas/produccion/SOLV2VIDA/config
fich_entrada_generadorTablasExp=GBT_TB340VTR0.TXT
fich_entrada_mensualizadorTasasAn=GBT_TB340VTA0.TXT

base=CIERRES
catalogos=CATALOGOS
ATR0=GBT_TB340ATR0.TXT
R340T000=FICHAS/FICHASPEND/FICHAGENTM.TXT
