#
########################################################################################################
#                                               MAPFRE                                                 #
########################################################################################################
#
# Auto-actualizacion de componentes en instancias de Amazon


SCRIPT_USER=awsadmin                            #Nombre del usuario que ejecuta el arranque de Coherence
CONFIG_FILE_NAME=act_config.txt                 #Nombre del fichero de configuracion de la actualizacion en el entorno
ACT_DIR=/mnt/solv2vida/software                 #Path del directorio con el software de actualizacion en el entorno Amazon
LOG_NAME=/logs/actualizacion.log
DIR_IP_OPEN=10.231.104.10                       #Direccion IP de la maquina Open donde se encuentran los ficheros de actualizacion
GROUP_OWNER=apps                                #Grupo propietario de la  instalacion de Coherence
USER_OWNER=awsadmin                             #Usuario propietario de la  instalacion de Coherence
