
########################################################################################################
#                                               MAPFRE                                                 #
########################################################################################################

LOG_NAME=/logs/actualizacion.log
SCRIPT_USER=awsadmin

