
####################################
#streams / fichero

FIC0=FICHAPROXY.TXT
PROXY_INC=INC_PROXY.TXT
PES0=PESOSBTPROXY.TXT

INC_GESINTRO=INC_GESINTRO_BT.TXT
GESINTRO_BT=VIDA_STROS_GESINTRO
GESINTRO=GESINTRO.TXT

INC_RTEVTOMAN=INC_RTE_VTO_MANUAL_DB2_BT.TXT
RTEVTOMAN_BT=VIDA_RESC_VCTOS_MAN
RTEVTOMAN=RTE_VTO_MANUAL_DB2.TXT

INC_RTEIND=INC_RTE_IND_IDMS_BT.TXT
RTEIND_BT=VIDA_RESC_INDV
RTEIND=RTE_IND_IDMS.TXT

INC_VTOIND=INC_VTO_IND_IDMS_BT.TXT
VTOIND_BT=VIDA_VCTOS_INDV
VTOIND=VTO_IND_IDMS.TXT

INC_RTEVTOCOL=INC_RTE_VTO_COL_IDMS_BT.TXT
RTEVTOCOL_BT=VIDA_RESC_VCTOS_COL
RTEVTOCOL=RTE_VTO_COL_IDMS.TXT

INC_ANTIND=INC_ANT_IND_IDMS_BT.TXT
ANTIND_BT=VIDA_ANTCP_IDMS
ANTIND=ANT_IND_IDMS.TXT

INC_AS400=INC_AS400_BT.TXT
AS400_BT=BMV_AS400
AS400=AS400.TXT

INC_ASEVAL=INC_ASEVAL_BT.TXT
ASEVAL_BT=BMV_ASEVAL
ASEVAL=ASEVAL.TXT

INC_RTANEO=INC_RTA_NEO_BT.TXT
RTANEO_BT=RENTASDB2
RTANEO=RTA_NEO.TXT

INC_MOVNEO=INC_MOV_NEO_BT.TXT
MOVNEO_BT=VIDA_MGM
MOVNEO=MOV_NEO.TXT

INC_PREONS=INC_PRE_ONS_BT.TXT
PREONS_BT=ONESAIT_VIDA
PREONS=PRE_ONS.TXT

INC_RTAINDTRAD=INC_RTA_IND_IDMS_TRAD_BT.TXT
RTAINDTRAD_BT=VIDA_RENTAS_TRAD
RTAINDTRAD=RTA_IND_IDMS_TRAD.TXT

INC_RTACOL=INC_RTA_COL_IDMS_BT.TXT
RTACOL_BT=VIDA_RENTAS_COL_IDMS
RTACOL=RTA_COL_IDMS.TXT