raiz=/explotacion/
jar_lib=${raiz}SOLV2VIDA/programas/produccion/SOLV2VIDA/lib/
raizNAS=/mnt/solv2vida/
raizSSAA=/mnt/ssaa/proxy/
ficheros=${raizNAS}PROXYVIDA/CIERRES/
ficherosPesos=${raizNAS}CIERRES/
dir_temporal=${ficheros}
dir_catalogos=${ficheros}
dir_salida=${ficheros}
dir_config=${raiz}SOLV2VIDA/programas/produccion/SOLV2VIDA/config

base=CIERRES
FIC0=FICHAPROXY.TXT