
catalogos=R340T000,GRE0,SCR0

####################################
#streams / fichero
SCR0=GBT_TB340SCR0.TXT
GRE0=GBT_TB340GRE0.TXT

R340T000=FICHAS/FICHASPEND/FICHAGENSCRGRE.TXT

INC0=INCIDENCIAS_GENSCRGRE.TXT
SAL0_AUX=GBT_TB340SCRGRE0.tmp
SAL0=GBT_TB340SCRGRE0.TXT