# Formato de los ficheros de salida. Posibles valores:
# txt      -> texto plano
# txt.gz   -> texto plano comprimido en formato gzip
formato.salida.fichero=txt.gz

# Exportar el detalle de corriente de manera distribuida o en un unico nodo
# (true->distribuido, false->un nodo)
exportar.detalle.corriente.distribuido=false