
catalogos=R340T000,VTA0,SCR0

####################################
#streams / fichero
VTA0=GBT_TB340VTA0.TXT
SCR0=GBT_TB340SCR0.TXT

R340T000=FICHAS/FICHASPEND/FICHAGENSCRAEP.TXT

INC0=INCIDENCIAS_GENSCRAEP.TXT
SAL0_AUX=GBT_TB340SCRAEP0.tmp
SAL0=GBT_TB340SCRAEP0.TXT