literalesBT.BTI=BTI
literalesBT.ROSSP=BTI,ROSSP
literalesBT.BEL=BTI,BEL
literalesBT.BTCOA=BTI,BTCOA
literalesBT.BELCOA=BTI,BELCOA
literalesBT.ROSSEAR=BTI,ROSSEAR
literalesBT.ROSSEARC=BTI,ROSSEARC
literalesBT.BELCLR=BTI,BELCLR
literalesBT.MULTI1=BTI,ROSSP,BELCLR
literalesBT.MULTICOA=BTI,BTCOA,BELCOA
literalesBT.MULTI2=BTI,BEL,SCRMFE,SCRMCF,SCRLFE,SCRTIU,SCRTID,SCRGTO,SCRAEP,SCRAEN,SCRANM,SCRINC
literalesBT.MULTI3=BTI,BEL,SCRMMI,SCRMCI,SCRVM,SCRLMI,SCRAIP,SCRAIN