
catalogos=ACI0,AIT0,ATA0,ATE0,ATR0,CTE0,DGI0,GAR0,ITG0,ITR0,MAD0,MVI0,VTA0

####################################
#streams / fichero
ACI0=/CATALOGOS/GBT_TB340ACI0.TXT
AIT0=/CATALOGOS/GBT_TB340AIT0.TXT
ATA0=/CATALOGOS/GBT_TB340ATA0.TXT
ATE0=/CATALOGOS/GBT_TB340ATE0.TXT
ATR0=/CATALOGOS/GBT_TB340ATR0.TXT
CTE0=/CATALOGOS/GBT_TB340CTE0.TXT
DGI0=/CATALOGOS/GBT_TB340DGI0.TXT
GAR0=/CATALOGOS/GBT_TB340GAR0.TXT
ITG0=/CATALOGOS/GBT_TB340ITG0.TXT
ITR0=/CATALOGOS/GBT_TB340ITR0.TXT
MAD0=/CATALOGOS/GBT_TB340MAD0.TXT
MVI0=/CATALOGOS/GBT_TB340MVI0.TXT
VTA0=/CATALOGOS/GBT_TB340VTA0.TXT
