# Definici�n de escenarios de Cartera Tecnica -> Num. Instancias Amazon
1I=escenario.A
1C=escenario.A
20I=escenario.B
20C=escenario.B
60I=escenario.C
60C=escenario.C


escenario.A=4
escenario.B=2
escenario.C=1

escenario.MAXIMO=4
nodos.coherence.instancia=12
