tasas-mensualizadas=GBT_TB340VMA0.TXT
R340T000=CATALOGOS/FICHAS/FICHASPEND/FICHAGENTA.TXT
LOG_FICHAS=CATALOGOS/FICHAS/FICHASPEND/LOGFICHAGENTA.TXT
INC0=INCIDENCIAS_GENTA.TXT
VTA0=CATALOGOS/GBT_TB340VTA0.TXT
