
####################################
#streams / fichero

FIC0=FICHATIREA.TXT

TOTPMACOABTI=BTI_TOTPMACOA.TXT
TOTPMACOAROSSP=ROSSP_TOTPMACOA.TXT
TOTPMACOABTCOATF=BTCOATF_TOTPMACOA.TXT

FLUJPMACOABTI=BTI_FLUJPMACOA.TXT
FLUJPMACOAROSSP=ROSSP_FLUJPMACOA.TXT
FLUJPMACOABTCOATF=BTCOATF_FLUJPMACOA.TXT

TIREA_INC=INC_TIREA.TXT
DATOSCOA=CTLG_DATOSCOA.TXT
TAB35012=CTLG_TAB35012.TXT

PROXY_INC=INC_PROXY.TXT