
####################################
#streams / fichero

FIC0=FICHATIREA.TXT

TOTPMACOABTI=BTI_TOTPMACOA.TXT
TOTPMACOABTCOA=BTCOA_TOTPMACOA.TXT
TOTPMACOABTCOATF=BTCOATF_TOTPMACOA.TXT

FLUJPMACOABTI=BTI_FLUJPMACOA.TXT
FLUJPMACOABTCOA=BTCOA_FLUJPMACOA.TXT
FLUJPMACOABTCOATF=BTCOATF_FLUJPMACOA.TXT

FLUJPMDCOABTI=BTI_FLUJPMDCOA.TXT
FLUJPMDCOABTCOA=BTCOA_FLUJPMDCOA.TXT
FLUJPMDCOABTCOATF=BTCOATF_FLUJPMDCOA.TXT

TIREA_INC=INC_TIREA.TXT
DATOSCOA=CTLG_DATOSCOA.TXT
TAB35012=CTLG_TAB35012.TXT
TAB35013=CTLG_TAB35013.TXT
TAB35014=CTLG_TAB35014.TXT
TAB35015=CTLG_TAB35015.TXT

DATOSESPECIFIC=GENCARTE_AUX_ESPECIFIC.TXT
PAGOSPLAN=GENCARTE_AUX_PAGOSPLAN.TXT