raiz=/explotacion/
jar_lib=${raiz}SOLV2VIDA/programas/produccion/SOLV2VIDA/lib/
raizNAS=/mnt/solv2vida/
ficheros=${raizNAS}TIREA/CIERRES/
ficherosTirea=${raizNAS}CIERRES/
dir_temporal=${ficherosTirea}FICHATIREA/
dir_catalogos=${ficheros}
dir_salida=${ficheros}
dir_config=${raiz}SOLV2VIDA/programas/produccion/SOLV2VIDA/config

base=CIERRES
FIC0=FICHATIREA.TXT