literalesBT.BTI=BTI
literalesBT.BTIPROY=BTIPROY,BEL
literalesBT.ROSSP=BTI,ROSSP
literalesBT.BEL=BTIPROY,BEL
literalesBT.BTCOA=BTI,BTCOA
literalesBT.BELCOA=BTIPROY,BELCOA
literalesBT.ROSSEAR=BTI,ROSSEAR
literalesBT.ROSSEARC=BTI,ROSSEARC
literalesBT.BELCLR=BTIPROY,BELCLR
literalesBT.MULTI1=BTIPROY,ROSSP,BELCLR
literalesBT.MULTICOA=BTIPROY,BTCOA,BELCOA
literalesBT.MULTI2=BTIPROY,BEL,SCRMFE,SCRLFE
#literalesBT.MULTI2=BTIPROY,BEL,SCRANM,SCRAEP,SCRAEN
#literalesBT.MULTI2=BTIPROY,BEL,SCRMFE,SCRLFE,SCRANM,SCRAEP,SCRAEN,SCRMCF,SCRGTO,SCRINC,SCRTIU,SCRTID
literalesBT.MULTI3=BTIPROY,BEL,SCRMMI,SCRMCI,SCRVM,SCRLMI,SCRAIP,SCRAIN
literalesBT.MULTI4C=BTIPROY,NIIF17,N17CLIR,NIIF17LIR,NIIF17OCI
literalesBT.MULTI4NB=BTIPROY,NIIF17,NIIF17LIR,NIIF17OCI
literalesBT.MULTI5=BTIPROY,N17LIRIN
literalesBT.NIIF17IF=BTIPROY,ROSSP,NIIF17IF
literalesBT.MULTI6=BTIPROY,ROSSPCSM,NIIF17LIR
literalesBT.MULTI7=BTI,ROSSP
literalesBT.MULTI8=BTIPROY,NIIF17,NIIF17LIR
literalesBT.MULTI8NB=BTIPROY,NIIF17,NIIF17LIR
literalesBT.BTCOATF=BTI,BTCOA,BTCOATF
literalesBT.MULTITB=BTI,ROSSPTE,ROSSPTI,ROSSPGA 
literalesBT.ROSSPTE=BTI,ROSSPTE
literalesBT.ROSSPTI=BTI,ROSSPTI
literalesBT.ROSSPGA=BTI,ROSSPGA