
catalogos=R340T000,IPC0,SCR0

####################################
#streams / fichero
IPC0=CTLG_TB880IPC0.TXT
SCR0=GBT_TB340SCR0.TXT

R340T000=FICHAS/FICHASPEND/FICHAGENSCRIPC.TXT

INC0=INCIDENCIAS_GENSCRIPC.TXT
SAL0_AUX=GBT_TB340SCRIPC0.tmp
SAL0=GBT_TB340SCRIPC0.TXT