raiz=/explotacion/
jar_lib=${raiz}SOLV2VIDA/programas/produccion/SOLV2VIDA/lib/
raizNAS=/mnt/solv2vida/
ficheros=${raizNAS}CIERRES/
dir_catalogos=${ficheros}CATALOGOS/
dir_temporal=${dir_catalogos}
dir_salida=${dir_catalogos}
dir_config=${raiz}SOLV2VIDA/programas/produccion/SOLV2VIDA/config
fich_entrada_generacion=${dir_catalogos}GBT_TB340NF17GRE0.TXT

base=CIERRES
catalogos=CATALOGOS
SCR0=GBT_TB340SCR0.TXT
GRE0=GBT_TB340GRE0.TXT
R340T000=FICHAS/FICHASPEND/FICHAGENNF17GRE.TXT
