<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>es.mapfre.scr</groupId>
  <artifactId>generacionSCRTablasExperiencia</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <name>generacionSCRTablasExperiencia</name>

  <dependencies>
    <dependency>
  		<groupId>org.apache.commons</groupId>
  		<artifactId>commons-lang3</artifactId>
  		<version>3.3.1</version>
  	</dependency>
  	<dependency>
  		<groupId>org.beanio</groupId>
  		<artifactId>beanio</artifactId>
  		<version>2.0.7</version>
  	</dependency>
  	<dependency>
		<groupId>org.slf4j</groupId>
		<artifactId>slf4j-api</artifactId>
		<version>1.7.7</version>
	</dependency>
	<dependency>
		<groupId>net.sf.ehcache</groupId>
		<artifactId>ehcache</artifactId>
		<version>2.9.0</version>
	</dependency>
  </dependencies>
  
  <build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>2.16</version>
					<configuration>
						<skipTests>true</skipTests>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<configuration>
						<source>1.7</source>
						<target>1.7</target>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<configuration>
						<archive>
							<manifest>
								<addClasspath>true</addClasspath>
								<mainClass>es.mapfre.scr.tablasExperiencia.modulos.PrincipalTExpSCRLFE</mainClass>
							</manifest>
						</archive>
						<archive>
							<manifest>
								<addClasspath>true</addClasspath>
								<mainClass>es.mapfre.scr.tablasExperiencia.modulos.PrincipalTExpSCRLMI</mainClass>
							</manifest>
						</archive>
						<archive>
							<manifest>
								<addClasspath>true</addClasspath>
								<mainClass>es.mapfre.scr.tablasExperiencia.modulos.PrincipalTExpSCRMFE</mainClass>
							</manifest>
						</archive>
						<archive>
							<manifest>
								<addClasspath>true</addClasspath>
								<mainClass>es.mapfre.scr.tablasExperiencia.modulos.PrincipalTExpSCRMMI</mainClass>
							</manifest>
						</archive>
						<archive>
							<manifest>
								<addClasspath>true</addClasspath>
								<mainClass>es.mapfre.scr.tablasExperiencia.modulos.PrincipalTExpSCRMCF</mainClass>
							</manifest>
						</archive>
						<archive>
							<manifest>
								<addClasspath>true</addClasspath>
								<mainClass>es.mapfre.scr.tablasExperiencia.modulos.PrincipalTExpSCRMCI</mainClass>
							</manifest>
						</archive>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>
