########################################################################################################
#                                               MAPFRE                                                 #
########################################################################################################

##-- Fichero de Configuracion del script de automatizacion
#--Datos del Entorno

USAR_VPN=false                                                  #Para iniciar la VPN establecer el valor true, de lo contrario false
SCRIPT_USER=awsadmin                                            #Nombre del usuario que ejecuta el script
OPEN_VPN=                                                       #Instance ID del nodo de VPN
TAG_ROLE_INSTANCE_MASTER=COHERENCE_SERVER_PRE					   #Tag Role del nodo Maestro
TAG_MASTER_INSTANCE_MASTER=TRUE								   #Tag Master del nodo Maestro
TAG_ROLE_INSTANCE=COHERENCE_SERVER_PRE							   #Tag Role de un nodo secundario
TAG_MASTER_INSTANCE=FALSE									   #Tag Master de un nodo secundario
# Instancias reservadas en nuevo VPC
#INSTANCE_ID1=i-3ea4fa94                                         #Instance ID del nodo maestro
#INSTANCE_ID2=i-07a4faad                                         #Instance ID de un nodo secundario
#INSTANCE_ID3=i-e9a5fb43          
#INSTANCE_ID4=i-05a4faaf          
MAX_INTENTOS=50                                                 #Numero de iteraciones para verificar el arranque de las instancias
# Instancias reservadas en nuevo VPC
#DIR_IP_MAESTRO=10.85.40.4                                     #Direccion IP privada del nodo maestro
#DIR_IP_2=10.85.40.5                                           #Direccion IP privada del nodo secundario
#DIR_IP_3=10.85.40.6
#DIR_IP_4=10.85.40.7
CERT=/opt/ec2-cert/SOLVENCIA2.pem             #Ubicacion del certificado de acceso a las instancias para el usuario que ejecuta el script
APP_OPEN="/explotacion/SOLV2VIDA/programas/produccion/SOLV2VIDA/lib/open-java-1.10.jar"             #Path a la aplicacion de OPEN
OPEN_LIB="/explotacion/SOLV2VIDA/programas/produccion/SOLV2VIDA/lib"                #Path al directorio lib en OPEN
OPEN_CONFIG="/explotacion/SOLV2VIDA/programas/produccion/SOLV2VIDA/config"          #Path al directorio config en OPEN
SCRIPT_HOME="/explotacion/SOLV2VIDA/programas/produccion/shs"                       #Directorio donde se ubican los script de automatizacion
RUTA_BASE_CIERRES=/mnt/solv2vida/CIERRES                        #Ruta a la carpeta base de cierres
RUTA_FICHA_LOG=FICHAS/FICHASPEND/LOGFICHACALC.TXT               #Esta variable permite definir la ubicacion del fichero de log de la aplicacion
LOG_PATH=/explotacion/ficheros/SOLV2VIDA/temporal               #Ubicacion del fichero de log de ejecucion del script de automatizacion
ENTORNO=pre                                                     #Definicion del entorno de ejecucion
INTER_INSTANCE=30s                                              #Tiempo de espera entre arranque de instancias secundarias en formato: number [suffix] s(seconds);m(minutes);h(hours);d(days)
AMAZON_LOG=true                                                 #Para realizar la copia de los logs ubicados en el directorio /logs del nodo maestro establecer el valor a true

#--Configuracion Timeouts del motor de calculo
INTERVAL=5s                           #Intervalo de verificacion del fichero de log de la aplicacion en formato: number [suffix] s(seconds);m(minutes);h(hours);d(days)
MAX=10                                #Numero de iteraciones en que se verificara el fichero de log. Se producira un timeout cuando se supere INTERVAL*MAX

