########################################################################################################
#                                               MAPFRE                                                 #
########################################################################################################

##-- Fichero de Configuracion del script de automatizacion
#--Datos del Entorno

USAR_VPN=true                                                  #Para iniciar la VPN establecer el valor true, de lo contrario false
SCRIPT_USER=awsadmin                                           #Nombre del usuario que ejecuta el script
OPEN_VPN=i-92deca25                                            #Instance ID del nodo de VPN    
TAG_ROLE_INSTANCE_MASTER=COHERENCE_SERVER					   #Tag Role del nodo Maestro
TAG_MASTER_INSTANCE_MASTER=TRUE								   #Tag Master del nodo Maestro
TAG_ROLE_INSTANCE=COHERENCE_SERVER							   #Tag Role de un nodo secundario
TAG_MASTER_INSTANCE=FALSE									   #Tag Master de un nodo secundario
MAX_INTENTOS=50                                                 #Numero de iteraciones para verificar el arranque de las instancias
CERT=/explotacion/SOLV2VIDA/programas/produccion/SOLV2VIDA/config/Desarrollo.pem              #Ubicacion del certificado de acceso a las instancias para el usuario que ejecuta el script
APP_OPEN="/explotacion/SOLV2VIDA/programas/produccion/SOLV2VIDA/lib/open-java-1.5-SNAPSHOT.jar"             #Path a la aplicacion de OPEN
OPEN_LIB="/explotacion/SOLV2VIDA/programas/produccion/SOLV2VIDA/lib"                #Path al directorio lib en OPEN
OPEN_CONFIG="/explotacion/SOLV2VIDA/programas/produccion/SOLV2VIDA/config"          #Path al directorio config en OPEN
SCRIPT_HOME="/explotacion/SOLV2VIDA/programas/produccion/shs"                       #Directorio donde se ubican los script de automatizacion
RUTA_BASE_CIERRES=/mnt/solv2vida/CIERRES                        #Ruta a la carpeta base de cierres
RUTA_FICHA_LOG=FICHAS/FICHASPEND/LOGFICHACALC.TXT               #Esta variable permite definir la ubicacion del fichero de log de la aplicacion
LOG_PATH=/explotacion/ficheros/SOLV2VIDA/temporal               #Ubicacion del fichero de log de ejecucion del script de automatizacion
ENTORNO=dev                                                      #Definicion del entorno de ejecucion
INTER_INSTANCE=30s                                               #Tiempo de espera entre arranque de instancias secundarias en formato: number [suffix] s(seconds);m(minutes);h(hours);d(days)
AMAZON_LOG=true                 				#Para realizar la copia de los logs ubicados en /logs en el nodo maestro establecer el valor a true

#--Configuracion Timeouts del motor de calculo
INTERVAL=10s                           #Intervalo de verificacion del fichero de log de la aplicacion en formato: number [suffix] s(seconds);m(minutes);h(hours);d(days)
MAX=25                                #Numero de iteraciones en que se verificara el fichero de log. Se producira un timeout cuando se supere INTERVAL*MAX

