# Definición de escenarios de Cartera Tecnica -> Num. Instancias Amazon
1I=escenario.A
1C=escenario.A
20I=escenario.A
20C=escenario.A
60I=escenario.B
60C=escenario.B


escenario.A=4
escenario.B=2
escenario.C=1

escenario.MAXIMO=24
nodos.coherence.instancia=12
