#Configuracion open-java
solvencia.ruta.base=/mnt/solv2vida

#propiedad para usar (S) o no (N) el paralelismo en la carga de ficheros
bbdd.carga.paralelismo.habilitar=N

#Configuracion BBDD
bbdd.host=scan1_crs_preproduccion2i_scan,scan2_crs_preproduccion2i_scan,scan3_crs_preproduccion2i_scan
bbdd.port=1534,1534,1534
bbdd.service_name=P_SGP_II

bbdd.user=SGP_APP
bbdd.password=SGPAPPII
bbdd.scheme=SGP_LD
bbdd.package=TOTALES

jmx.url=service:jmx:rmi://10.251.135.5:3000/jndi/rmi://10.251.135.5:9000/server