#Configuracion open-java
solvencia.ruta.base=/mnt/solv2vida

#propiedad para usar (S) o no (N) el paralelismo en la carga de ficheros
bbdd.carga.paralelismo.habilitar=N

#Configuracion BBDD
bbdd.host=scan1_crs_produccion3i_scan.es.mapfre.net,scan2_crs_produccion3i_scan.es.mapfre.net,scan3_crs_produccion3i_scan.es.mapfre.net
bbdd.port=1534,1534,1534
bbdd.service_name=R_SGP_II

bbdd.user=SGP_APP
bbdd.password=SGP360APP
bbdd.scheme=SGP_LD
bbdd.package=TOTALES

jmx.url=service:jmx:rmi://10.251.135.21:3000/jndi/rmi://10.251.135.21:9000/server