#Configuracion open-java
solvencia.ruta.base=/mnt/solv2vida

#propiedad para usar (S) o no (N) el paralelismo en la carga de ficheros
bbdd.carga.paralelismo.habilitar=N

#Configuracion BBDD
bbdd.host=172.22.213.137
bbdd.port=1521
bbdd.service_name=MAPRSII

bbdd.user=
bbdd.password=
bbdd.scheme=
bbdd.package=TOTALES

jmx.url=service:jmx:rmi://10.0.1.11:3000/jndi/rmi://10.0.1.11:9000/server