#
########################################################################################################
#                                               MAPFRE                                                 #
########################################################################################################
#
#Fichero de configuracion del entorno

ENTORNO=pre
