umics.bloque=2500
ruta.botes=CTEC/BOTE


mensajes.errores=ERR0
auxiliares=X880J003,X880JI03,X880JI04,X880J009,X880J004,X880J005,PTIPO,TABLA2000,X880J007
catalogos=DPR0,VMA0,DPG,DIP0,SOL0,AUX0,IPC0,TXP0,CTM0,VCR0,RW06646,X880JI08,FLP0,OPG0,VTR0,GRE0,VCI0,CTU0,COM0,INV0,SWCOBROCOMISIONES,SWCOBROCOM,HTR0,TAB923,TAB35050
catalogos-multi2=DPR0,VMA0,DPG,DIP0,SOL0,AUX0,IPC0,TXP0,CTM0,VCR0,RW06646,X880JI08,FLP0,OPG0,VTR0,GRE0,VCI0,COM0,INV0,SCR0,SCRGRE0,SCRIPC0,SCRAEP0,SCRAEN0,SCRMFE0,SCRMCF0,SCRLFE0
catalogos-multi3=DPR0,VMA0,DPG,DIP0,SOL0,AUX0,IPC0,TXP0,CTM0,VCR0,RW06646,X880JI08,FLP0,OPG0,VTR0,GRE0,VCI0,COM0,INV0,SCR0,SCRAIP0,SCRAIN0,SCRMMI0,SCRMCI0,SCRLMI0
catalogos-all=DPR0,VMA0,DPG,DIP0,SOL0,AUX0,IPC0,TXP0,CTM0,VCR0,RW06646,X880JI08,FLP0,OPG0,VTR0,GRE0,VCI0,CTU0,COM0,INV0,SCR0,SCRGRE0,SCRIPC0,SCRAEP0,SCRAEN0,SCRAIP0,SCRAIN0,SCRMFE0,SCRMMI0,SCRMCF0,SCRMCI0,SCRLFE0,SCRLMI0,NF17AEN0,NF17GRE0,NF17MFE0
catalogos-multisn=DPR0,VMA0,DPG,DIP0,SOL0,AUX0,IPC0,TXP0,CTM0,VCR0,RW06646,X880JI08,FLP0,OPG0,VTR0,GRE0,VCI0,CTU0,COM0,INV0,SCR0,NF17AEN0,NF17GRE0,NF17MFE0

salida=totales-flujos,detalle-basetecnicas,detalle-corriente,incidencias,incidenciasmaestro
fichaSalida=R340T003

####################################
#streams / fichero

TXP0=/CATALOGOS/CTLG_TB005TXP0.TXT
X880J009=/CTEC/GENCARTE_AUX_AMORTIZ.TXT
X880JI08=/CATALOGOS/CTLG_X880JI08.TXT
X880J004=/CTEC/GENCARTE_AUX_ESPECIFIC.TXT
X880JI03=/CTEC/GENCARTE_AUX_DATOSCOA.TXT
X880JI04=/CTEC/GENCARTE_AUX_PBTECNI.TXT
TABLA2000=/CTEC/GENCARTE_AUX_TAB2000.TXT
DPR0=/CATALOGOS/CTLG_TB880DPR0.TXT
DPG=/CATALOGOS/CTLG_TB880DPG0.TXT
AUX0=/CATALOGOS/CTLG_TB880AUX0.TXT
SOL0=/CATALOGOS/CTLG_TB880SOL0.TXT
DIP0=/CATALOGOS/CTLG_TB880DIP0.TXT
R340T000=/FICHAS/FICHASPEND/FICHASCALCULO.TXT
FLP0=/CATALOGOS/CTLG_TB880FLP0.TXT
IPC0=/CATALOGOS/CTLG_TB880IPC0.TXT
RW06646=/CATALOGOS/CTLG_RW06646.TXT
ERR0=/CATALOGOS/CTLG_TB340ERR0.TXT
X880J003=/CTEC/GENCARTE_AUX_PAGOSPLAN.TXT
OPG0=/CATALOGOS/CTLG_TB880OPG0.TXT
CTM0=/CATALOGOS/CTLG_TB005CTM0.TXT
VMA0=/CATALOGOS/GBT_TB340VMA0.TXT
COM0=/CATALOGOS/GBT_TB880COM0.TXT

X880J005=/CTEC/GENCARTE_AUX_VLIQUID.TXT
X880J007=/CTEC/GENCARTE_AUX_INSTRUMENTALES.TXT
VCR0=/CATALOGOS/CTLG_TB310VCR0.TXT
VTR0=/CATALOGOS/GBT_TB340VTR0.TXT
GRE0=/CATALOGOS/GBT_TB340GRE0.TXT
VCI0=/CATALOGOS/GBT_TB340VCI0.TXT
CTU0=/CATALOGOS/GBT_TB340CTU0.TXT

INV0=/CATALOGOS/GBT_TB340INV0.TXT

HTR0=/CATALOGOS/GBT_TB340HTR0.TXT

TAB923=/CATALOGOS/TAB923.TXT

TAB35050=/CATALOGOS/TAB35050.TXT

SCR0=/CATALOGOS/GBT_TB340SCR0.TXT
SCRIPC0=/CATALOGOS/GBT_TB340SCRIPC0.TXT
SCRGRE0=/CATALOGOS/GBT_TB340SCRGRE0.TXT
SCRMFE0=/CATALOGOS/GBT_TB340SCRMFE0.TXT
SCRMMI0=/CATALOGOS/GBT_TB340SCRMMI0.TXT
SCRMCF0=/CATALOGOS/GBT_TB340SCRMCF0.TXT
SCRMCI0=/CATALOGOS/GBT_TB340SCRMCI0.TXT
SCRLFE0=/CATALOGOS/GBT_TB340SCRLFE0.TXT
SCRLMI0=/CATALOGOS/GBT_TB340SCRLMI0.TXT
SCRAEP0=/CATALOGOS/GBT_TB340SCRAEP0.TXT
SCRAEN0=/CATALOGOS/GBT_TB340SCRAEN0.TXT
SCRAIP0=/CATALOGOS/GBT_TB340SCRAIP0.TXT
SCRAIN0=/CATALOGOS/GBT_TB340SCRAIN0.TXT

NF17GRE0=/CATALOGOS/GBT_TB340NF17GRE0.TXT
NF17MFE0=/CATALOGOS/GBT_TB340NF17MFE0.TXT
NF17AEN0=/CATALOGOS/GBT_TB340NF17AEN0.TXT

SWCOBROCOMISIONES=/CATALOGOS/P0341010_COMIS_POLANUAL.TXT

SWCOBROCOM=/CATALOGOS/SWCOBROCOM.TXT

X880JI01=/CTEC/GENCARTE_MAESTRO_UNIFICADO.TXT


R340T003=/FICHAS/FICHASPEND/LOGFICHACALC.TXT
detalle-corriente=FLUJOSDET
detalle-basetecnicas=MAESBTC
totales-flujos=FLUJOSTOT
incidencias=INCIDENCIAS
incidenciasmaestro=INCIDENCIASMAESTRO

PTIPO=/CTEC/GENCARTE_PTIPO.TXT

prvinf1=PRVINF1
prvinf2=PRVINF2
prvumic=PRVUMIC
prvcr=PRVCR
prvbt=PRVBT
flujinf1=FLUJINF1
flujinf2=FLUJINF2
provcoaseg=PROVCOASEG
flujcoaseg=FLUJCOASEG
basetec=BASETEC
prvfpb=PRVFPB
flujtcas=FLUJTCAS
contab=CONTAB
scrvm=SCRVM
flujostotp=FLUJOSTOTP
flujinf3=FLUJINF3
flujinf4=FLUJINF4
flujostn17=FLUJOSTN17
fpsl=FPSL
flujototpv=FLUJOTOTPV
patroncsm=PATRONCSM
pesosbt=PESOSBT
pesosbtproxy=PESOSBTPROXY
swcobrocom =SWCOBROCOM
swcobrocomcsv =SWCOBROCOMCSV
totpmacoa=TOTPMACOA
flujpmacoa=FLUJPMACOA
flujpmdcoa=FLUJPMDCOA
totpmacoam=TOTPMACOAM
flujpmacoam=FLUJPMACOAM
flujpmdcoam=FLUJPMDCOAM
contcerti=CONTCERTI
flujinfscr=FLUJINFSCR
contabc=CONTABC
flujsuscri=FLUJSUSCRI