
catalogos=R340T000,TXP0,CTM0,ATR0

####################################
#streams / fichero
TXP0=CTLG_TB005TXP0.TXT
CTM0=CTLG_TB005CTM0.TXT
ATR0=GBT_TB340ATR0.TXT
#R340T000=FICHASCALCULO.TXT
R340T000=FICHAS/FICHASPEND/FICHAGENTM.TXT

INC0=INCIDENCIAS_GENTM.TXT
SAL_AUX=GBT_TB340VTR0.tmp
SAL0=GBT_TB340VTR0.TXT