<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	
	<groupId>es.mapfre.solvencia</groupId>
	<artifactId>motor-programas</artifactId>
	<version>11.0.0-RELEASE</version>
	<packaging>jar</packaging>

	<parent>
		<groupId>es.mapfre.solvencia</groupId>
		<artifactId>solvencia</artifactId>
		<version>11.0.0-RELEASE</version>
		<relativePath>../solvencia</relativePath>
	</parent>

	<name>Motor - Programas</name>
	<url>http://www.mapfre.es</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version.source>1.7</java.version.source>
		<java.version.target>1.7</java.version.target>
	</properties>
	
  <dependencies>
		<!-- Mapfre Solvencia -->
		<dependency>
			<groupId>es.mapfre.solvencia</groupId>
			<artifactId>modelo</artifactId>
		</dependency>
		<dependency>
			<groupId>es.mapfre.solvencia</groupId>
			<artifactId>excepciones</artifactId>
		</dependency>
  </dependencies>
</project>
