raiz=/explotacion/
jar_lib=${raiz}SOLV2VIDA/programas/produccion/SOLV2VIDA/lib/
raizNAS=/mnt/solv2vida/
ficheros=${raizNAS}CIERRES/
dir_catalogos=${ficheros}CATALOGOS/
dir_temporal=${dir_catalogos}
dir_salida=${dir_catalogos}
dir_config=${raiz}SOLV2VIDA/programas/produccion/SOLV2VIDA/config
fich_entrada_generacion=${dir_catalogos}GBT_TB340NF17MFE0.TXT

base=CIERRES
catalogos=CATALOGOS
ATR0=GBT_TB340ATR0.TXT
TXP0=CTLG_TB005TXP0.TXT
CTM0=CTLG_TB005CTM0.TXT
SCR0=GBT_TB340SCR0.TXT
R340T000=FICHAS/FICHASPEND/FICHAGENNF17MFE.TXT
