#Configuracion open-java
solvencia.ruta.base=C\:\\NAS

#propiedad para usar (S) o no (N) el paralelismo en la carga de ficheros
bbdd.carga.paralelismo.habilitar=N

#Configuracion BBDD
bbdd.host=172.22.213.137
bbdd.port=1521
bbdd.service_name=MAPRSII

bbdd.user=solvencia
bbdd.password=indra2014
bbdd.scheme=SOLVENCIA_LD
bbdd.package=TOTALES

jmx.url=service:jmx:rmi://localhost:3000/jndi/rmi://localhost:9000/server